### ISSUE TITLE
Various improvements to python-template

### ISSUE THREAD

**Issue by markgreene74** [markgreene74/python-template#25]
- [x] Update the directory structure #30 
- [x] Install `pre-commit` and add `pre-commit-config.yaml` #26 
  - `black`
  - `isort`
  - `autoflake`
- [x] Add PR and issues templates #28 
- [x] Add GH workflows #28 
  - [x] Add a [`cache` action](https://github.com/marketplace/actions/cache), see documentation [here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) and here
- [x] Add `devcontainer.json` #27
- [x] Add the MIT License file

For the new directory structure, see here for reference: https://realpython.com/python-application-layouts/#application-with-internal-packages

The new directory structure should look like this:
```
python-template/
│
│
├── docs/
│   ├── package_01.md
│   └── package_02.md
│
├── application/
│   ├── __init__.py
│   ├── main.py
│   ├── package_01/
│   │   ├── __init__.py
│   │   ├── helpers.py
│   │   └── something.py
│   │
│   └── package_02/
│       ├── __init__.py
│       ├── helpers.py
│       └── something_else.py
│
├── data/
│   └── data.csv
│
├── tests/
│   ├── package_01
│   │   ├── helpers_tests.py
│   │   └── something_tests.py
│   │
│   └── package_02/
│       ├── helpers_tests.py
│       └── something_else_tests.py
│
├── .gitignore
├── LICENSE
└── README.md
```

**Comment by markgreene74** [comment]
Useful reads for the Cache action:
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
- https://github.com/marketplace/actions/cache

Useful reads for using Poetry in a GH action
- https://jacobian.org/til/github-actions-poetry/
- https://python-poetry.org/docs/#ci-recommendations
